In [2]:

import pandas as pd

illegal = pd.read_csv('../resources/illegal_parking.csv')

In [3]:
illegal

            연번        단속일자      단속시간          단속장소     단속구분     데이터 기준일
0            1  2024-01-01  09:30:00  조치원역광장-버스정류장  고정형CCTV  2025-07-31
1            2  2024-01-01  11:37:00  조치원역광장-택시승강장  고정형CCTV  2025-07-31
2            3  2024-01-01  13:29:00  조치원역광장-택시승강장  고정형CCTV  2025-07-31
3            4  2024-01-01  14:59:00  해들마을6단지교차로주변  고정형CCTV  2025-07-31
4            5  2024-01-01  16:22:00     세종교육청앞삼거리  고정형CCTV  2025-07-31
...        ...         ...       ...           ...      ...         ...
127430  127431  2025-07-23  11:18:51    새샘마을3단지정문앞  고정형CCTV  2025-07-31
127431  127432  2025-07-23  15:17:21     고운동 고운뜰4길  주행형CCTV  2025-07-31
127432  127433  2025-07-24  13:05:54  새솔유치원-놀이터삼거리  고정형CCTV  2025-07-31
127433  127434  2025-07-24  15:04:15   조치원읍 죽림로 부근  주행형CCTV  2025-07-31
127434  127435  2025-07-24  16:15:47  세종시립도서관-상가주변  고정형CCTV  2025-07-31

[127435 rows x 6 columns]

In [4]:
illegal[illegal['단속장소'].str.contains('D_Name', na=False)]

          연번        단속일자      단속시간           단속장소     단속구분     데이터 기준일
2917    2918  2024-01-24  17:14:00   D_Name 용포외곽길  주행형CCTV  2025-07-31
2918    2919  2024-01-24  17:14:00   D_Name 용포외곽길  주행형CCTV  2025-07-31
2919    2920  2024-01-24  17:15:00   D_Name 용포외곽길  주행형CCTV  2025-07-31
5980    5981  2024-01-24  17:13:00   D_Name 용포외곽길  주행형CCTV  2025-07-31
5981    5982  2024-01-24  17:14:00  D_Name 대평시장2길  주행형CCTV  2025-07-31
...      ...         ...       ...            ...      ...         ...
92134  92135  2025-02-20  10:11:17   D_Name 용포외곽길  주행형CCTV  2025-07-31
92135  92136  2025-02-20  15:32:14   D_Name 명학산단로  주행형CCTV  2025-07-31
92136  92137  2025-02-20  15:32:19   D_Name 명학산단로  주행형CCTV  2025-07-31
93649  93650  2025-02-24  09:40:18   D_Name 부강금호로  주행형CCTV  2025-07-31
93650  93651  2025-02-24  09:43:41   D_Name 부강금호로  주행형CCTV  2025-07-31

[310 rows x 6 columns]

In [5]:
region_map = {
    '한솔': '한솔동',
    '새롬': '새롬동',
    '나성': '나성동',
    '다정': '다정동',
    '도담': '도담동',
    '어진': '어진동',
    '해밀': '해밀동',
    '아름': '아름동',
    '종촌': '종촌동',
    '고운': '고운동',
    '보람': '보람동',
    '대평': '대평동',
    '소담': '소담동',
    '반곡': '반곡동',
    '가람': '가람동',
    
    '용포외곽길':'금남면',
    '세종시립도서관':'고운동',
    '세종교육청':'보람동',
    '새샘':'소담동',
    '새솔유치원':'다정동',
    '해들':'대평동',
    '범지기':'아름동',
    '새뜸':'새롬동',
    '가온':'다정동',
    '보건복지부':'어진동',
    '코스트코':'대평동',
    '국민은행첫마을지점':'나성동',
    '축산물품질평가원':'아름동',
    '국민권익위원회':'어진동',
    '호려울마을4단지':'보람동',
    '명동초':'조치원읍',
    '대영프라자':'아름동',
    '가재마을5단지':'종촌동',
    '대수약국':'조치원읍',
    '에반아트리움':'나성동',
    '어반아트리움':'나성동',
    '보건환경연구원':'조치원읍',
    '수루배마을':'반곡동',
    '호려울마을':'보람동',
    '나릿재':'나성동',
    '행정안전부':'어진동',
    '첫마을':'한솔동',
    '새나루':'집현동',
    '도시통합정보센터':'조치원읍',
    '삼일아파트':'조치원읍',
    '도램마을':'도담동',
    '센트럴타워':'나성동',
    '원리119':'조치원읍',
    '국무총리':'어진동',
    '한결초':'다정동',
    '온빛초':'고운동',
    '농림축산식품부':'어진동',
    '정부청사':'어진동',
    '양지':'도담동',
    '가재':'종촌동',
    '두루':'고운동',
    '봉암자율방범대':'연서면',
    '늘봄초등학교':'도담동',
    '여울초':'보람동',
    '한뜰마을':'어진동',
    '가락마을':'고운동',
    '성프란치스코성당':'고운동',
    '마크원에비뉴':'나성동',
    '연남초':'연기면',
    '도원초':'연서면',
    '가락유치원':'고운동',
    '백두산빌딩':'종촌동',
    '국세청':'나성동',
    '교동초':'조치원읍',
    '나래초':'아름동',
    '참샘유치원':'한솔동',
    '금강프라자':'나성동',
    '산업통상자원부':'어진동',
    '신봉초등학교':'조치원읍',
    '엠브릿지사거리':'어진동',
    '명학리 978':'연동면',
    '치원읍':'조치원읍',
    '명학산단로':'연동면',
    '명학산단서로':'연동면',
    '명학산단남로':'연동면',
    '명학산단1로':'연동면',
    '원합강1길':'연동면',
    '발산1길':'금남면',
    '부촌길':'부강면',
    '용포중앙2길':'금남면',
    '퇴미로':'부강면',

    '산울': '산울동',
    '집현': '집현동',
    '세종': '세종동',
    '한별': '한별동',

    '조치원': '조치원읍',

    '연기': '연기면',
    '연동': '연동면',
    '부강': '부강면',
    '금남': '금남면',
    '장군': '장군면',
    '연서': '연서면',
    '전의': '전의면',
    '전동': '전동면',
    '소정': '소정면'
}

In [6]:
def classify_region(place):
    place = str(place)

    for keyword, region in region_map.items():
        if keyword in place:
            return region

    return '미분류'

In [7]:
illegal['지역'] = illegal['단속장소'].apply(classify_region)
illegal

            연번        단속일자      단속시간          단속장소     단속구분     데이터 기준일    지역
0            1  2024-01-01  09:30:00  조치원역광장-버스정류장  고정형CCTV  2025-07-31  조치원읍
1            2  2024-01-01  11:37:00  조치원역광장-택시승강장  고정형CCTV  2025-07-31  조치원읍
2            3  2024-01-01  13:29:00  조치원역광장-택시승강장  고정형CCTV  2025-07-31  조치원읍
3            4  2024-01-01  14:59:00  해들마을6단지교차로주변  고정형CCTV  2025-07-31   대평동
4            5  2024-01-01  16:22:00     세종교육청앞삼거리  고정형CCTV  2025-07-31   보람동
...        ...         ...       ...           ...      ...         ...   ...
127430  127431  2025-07-23  11:18:51    새샘마을3단지정문앞  고정형CCTV  2025-07-31   소담동
127431  127432  2025-07-23  15:17:21     고운동 고운뜰4길  주행형CCTV  2025-07-31   고운동
127432  127433  2025-07-24  13:05:54  새솔유치원-놀이터삼거리  고정형CCTV  2025-07-31   다정동
127433  127434  2025-07-24  15:04:15   조치원읍 죽림로 부근  주행형CCTV  2025-07-31  조치원읍
127434  127435  2025-07-24  16:15:47  세종시립도서관-상가주변  고정형CCTV  2025-07-31   고운동

[127435 rows x 7 columns]

In [8]:
#미분류 행 몇개
(illegal['지역'] == '미분류').sum()

1132

In [9]:
unclassified = illegal[illegal['지역'] == '미분류']
unclassified['단속장소'].value_counts()

단속장소
제일풍경채 주변    914
복지회관앞5거리    218
Name: count, dtype: int64

In [16]:
#미분류 된 데이터 삭제
illegal = illegal[illegal['지역'] != '미분류']

In [17]:
#어느 동이 주차단속이 많을까

illegal['지역'].value_counts()

지역
조치원읍    28321
고운동     15164
어진동     11016
아름동     10572
나성동      9780
다정동      8908
새롬동      7922
도담동      4480
대평동      4065
보람동      3352
세종동      3194
소담동      3086
해밀동      2748
한솔동      2308
집현동      2265
반곡동      1935
소정면      1627
종촌동      1547
금남면      1219
연동면       944
부강면       578
연서면       418
산울동       389
전의면       210
연기면       138
장군면        50
전동면        35
가람동        30
한별동         2
Name: count, dtype: int64

In [18]:
import plotly.express as px

region_df = illegal['지역'].value_counts().reset_index()
region_df.columns = ['지역', '단속건수']

fig = px.bar(
    region_df,
    x='지역',
    y='단속건수',
    text='단속건수',
    title='전체 지역별 불법주정차 단속 건수'
)

fig.update_layout(
    xaxis_title='지역',
    yaxis_title='단속 건수',
    xaxis_tickangle=-45,
    width=1200,
    height=600
)

fig.show()

1033

1679

1303

단속구분
고정형CCTV     89023
주행형CCTV     20703
안전신문고       15976
국민신문고         921
민원(공익제보)      812
Name: count, dtype: int64