In [26]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib

matplotlib.rcParams['font.family'] = 'AppleGothic', 'Malgun Gothic', 'NanumGothic', 'Sans-serif'
matplotlib.rcParams['axes.unicode_minus'] = False

In [27]:
parking_locations = pd.read_csv("../data/processed/parking_lot_locations.csv")
parking_locations.head()

   Unnamed: 0      주차장 명칭  주차구획수         위도          경도
0           0        죽림리3     29  36.591358  127.297680
1           1        죽림리4     22  36.592130  127.295639
2           2         남리1     45  36.594587  127.299663
3           3         상리1    131  36.601868  127.302626
4           4  세종전통시장주차타워    149  36.599828  127.299317

In [28]:
df = pd.read_csv('../data/processed/illegal_top_places.csv', encoding='utf-8-sig')
df

      지역             단속장소  단속건수
0    나성동        국민은행첫마을지점  1709
1    나성동      나성동 현대자동차인근  1567
2    나성동     나성동 세종행복타워주변  1498
3    나성동         나성동 메가박스   535
4    나성동         에반아트리움뒤편   492
5    도담동       도담동 먹자골목인근  1580
6    도담동           도담복컴주변   611
7    도담동        도담동 도담서4길   516
8    도담동       양지고등학교 삼거리   212
9    도담동           양지초등학교   204
10   보람동     호려울마을4단지앞사거리   923
11   보람동        세종교육청앞삼거리   611
12   보람동    호려울마을8-9단지사거리   432
13   보람동     보람동 금강시티타워 사   311
14   보람동        보람지구대 사거리   300
15   소담동       새샘마을3단지정문앞   736
16   소담동     새샘마을5단지501동앞   563
17   소담동    새샘마을2단지218동주변   267
18   소담동         소담동 법원4로   236
19   소담동     소담동 아이콤타워삼거리   171
20   아름동     축산물품질평가원 삼거리  3292
21   아름동     범지기마을 6단지 부근  3284
22   아름동          대영프라자부근   578
23   아름동           아름동교차로   409
24   아름동        아름유치원 삼거리   369
25  조치원읍     조치원역광장-버스정류장  2658
26  조치원읍         조치원농협사거리  2000
27  조치원읍     조치원역광장-택시승강장  1778
28  조치원읍      조치원읍 으뜸길 부근  1295
29  조치원읍     조치원읍 시민회관네거리  1138
30   한솔동            한솔파출소   536
31   한솔동     한솔동 940 횡단보도   408
32   한솔동         첫마을4단지주변   347
33   한솔동  첫마을301동-308동 사이   118
34   한솔동      한솔동 1230 인도   110

In [29]:
lat_map = {
    '국민은행첫마을지점': 36.4820796620759,
    '나성동 현대자동차인근': 36.4906871212038,
    '나성동 세종행복타워주변': 36.4802362669873,
    '나성동 메가박스': 36.4834762900916,
    '에반아트리움뒤편': 36.48877167500176,
    '도담동 먹자골목인근': 36.5143054345153,
    '도담복컴주변': 36.515523,
    '도담동 도담서4길': 36.5178442,
    '양지고등학교 삼거리': 36.5094908,
    '양지초등학교': 36.5183771731292,
    '호려울마을4단지앞사거리': 36.4756911625585,
    '세종교육청앞삼거리': 36.4796639273676,
    '호려울마을8-9단지사거리': 36.4787369772013,
    '보람동 금강시티타워 사': 36.4780567063485,
    '보람지구대 사거리': 36.4777868098303,
    '새샘마을3단지정문앞': 36.4839403498066,
    '새샘마을5단지501동앞': 36.4810990980914,
    '새샘마을2단지218동주변': 36.4822001156159,
    '소담동 법원4로': 36.4863609098117,
    '소담동 아이콤타워삼거리': 36.4844837203423,
    '축산물품질평가원 삼거리': 36.5134212407477,
    '범지기마을 6단지 부근': 36.5103946248234,
    '대영프라자부근': 36.5116131434761,
    '아름동교차로': 36.5277621388233,
    '아름유치원 삼거리': 36.5151122,
    '조치원역광장-버스정류장': 36.6012755661504,
    '조치원농협사거리': 36.595573185949725,
    '조치원역광장-택시승강장': 36.6003958331519,
    '조치원읍 으뜸길 부근': 36.6007175707786,
    '조치원읍 시민회관네거리': 36.6031468009938,
    '한솔파출소': 36.4802586472054,
    '한솔동 940 횡단보도': 36.4814511970931,
    '첫마을4단지주변': 36.4806173109339,
    '첫마을301동-308동 사이': 36.4781897438999,
    '한솔동 1230 인도': 36.4794042533264
}

lon_map = {
    '국민은행첫마을지점': 127.260502652606,
    '나성동 현대자동차인근': 127.256904102361,
    '나성동 세종행복타워주변': 127.261813684858,
    '나성동 메가박스': 127.263778376604,
    '에반아트리움뒤편': 127.26238746868874,
    '도담동 먹자골목인근': 127.258602129546,
    '도담복컴주변': 127.2618168,
    '도담동 도담서4길': 127.2558658,
    '양지고등학교 삼거리': 127.2689048,
    '양지초등학교': 127.260397855502,
    '호려울마을4단지앞사거리': 127.288776593893,
    '세종교육청앞삼거리': 127.286041678744,
    '호려울마을8-9단지사거리': 127.297005294865,
    '보람동 금강시티타워 사': 127.288440010959,
    '보람지구대 사거리': 127.291001023963,
    '새샘마을3단지정문앞': 127.296860886969,
    '새샘마을5단지501동앞': 127.305709676877,
    '새샘마을2단지218동주변': 127.299066118088,
    '소담동 법원4로': 127.303431985079,
    '소담동 아이콤타워삼거리': 127.299181022153,
    '축산물품질평가원 삼거리': 127.242770151552,
    '범지기마을 6단지 부근': 127.248762639454,
    '대영프라자부근': 127.243620742044,
    '아름동교차로': 127.248827618922,
    '아름유치원 삼거리': 127.244847,
    '조치원역광장-버스정류장': 127.296956432571,
    '조치원농협사거리': 127.29549293686254,
    '조치원역광장-택시승강장': 127.295377213202,
    '조치원읍 으뜸길 부근': 127.297068850747,
    '조치원읍 시민회관네거리': 127.300686537177,
    '한솔파출소': 127.259032613349,
    '한솔동 940 횡단보도': 127.259840040033,
    '첫마을4단지주변': 127.252173694495,
    '첫마을301동-308동 사이': 127.259499524175,
    '한솔동 1230 인도': 127.254807601128
}

df['위도'] = df['단속장소'].map(lat_map)
df['경도'] = df['단속장소'].map(lon_map)

df

      지역             단속장소  단속건수         위도          경도
0    나성동        국민은행첫마을지점  1709  36.482080  127.260503
1    나성동      나성동 현대자동차인근  1567  36.490687  127.256904
2    나성동     나성동 세종행복타워주변  1498  36.480236  127.261814
3    나성동         나성동 메가박스   535  36.483476  127.263778
4    나성동         에반아트리움뒤편   492  36.488772  127.262387
5    도담동       도담동 먹자골목인근  1580  36.514305  127.258602
6    도담동           도담복컴주변   611  36.515523  127.261817
7    도담동        도담동 도담서4길   516  36.517844  127.255866
8    도담동       양지고등학교 삼거리   212  36.509491  127.268905
9    도담동           양지초등학교   204  36.518377  127.260398
10   보람동     호려울마을4단지앞사거리   923  36.475691  127.288777
11   보람동        세종교육청앞삼거리   611  36.479664  127.286042
12   보람동    호려울마을8-9단지사거리   432  36.478737  127.297005
13   보람동     보람동 금강시티타워 사   311  36.478057  127.288440
14   보람동        보람지구대 사거리   300  36.477787  127.291001
15   소담동       새샘마을3단지정문앞   736  36.483940  127.296861
16   소담동     새샘마을5단지501동앞   563  36.481099  127.305710
17   소담동    새샘마을2단지218동주변   267  36.482200  127.299066
18   소담동         소담동 법원4로   236  36.486361  127.303432
19   소담동     소담동 아이콤타워삼거리   171  36.484484  127.299181
20   아름동     축산물품질평가원 삼거리  3292  36.513421  127.242770
21   아름동     범지기마을 6단지 부근  3284  36.510395  127.248763
22   아름동          대영프라자부근   578  36.511613  127.243621
23   아름동           아름동교차로   409  36.527762  127.248828
24   아름동        아름유치원 삼거리   369  36.515112  127.244847
25  조치원읍     조치원역광장-버스정류장  2658  36.601276  127.296956
26  조치원읍         조치원농협사거리  2000  36.595573  127.295493
27  조치원읍     조치원역광장-택시승강장  1778  36.600396  127.295377
28  조치원읍      조치원읍 으뜸길 부근  1295  36.600718  127.297069
29  조치원읍     조치원읍 시민회관네거리  1138  36.603147  127.300687
30   한솔동            한솔파출소   536  36.480259  127.259033
31   한솔동     한솔동 940 횡단보도   408  36.481451  127.259840
32   한솔동         첫마을4단지주변   347  36.480617  127.252174
33   한솔동  첫마을301동-308동 사이   118  36.478190  127.259500
34   한솔동      한솔동 1230 인도   110  36.479404  127.254808

In [30]:
import folium

nasung_map = folium.Map(location=[36.483, 127.26], zoom_start=16)

df_nasung = df[(df['지역'] == '나성동') & df['위도'].notna() & df['경도'].notna()]

for _, row in df_nasung.iterrows():
    radius_scale = row['단속건수'] * 0.05
    popup_text = f"{row['단속장소']}<br><b>단속건수:</b> {row['단속건수']}건"
    
    folium.CircleMarker(
        location=[row['위도'], row['경도']],
        radius=radius_scale,            # 단속건수별 크기 동적 조절
        popup=folium.Popup(popup_text, max_width=300),
        color='red',                    # 원의 테두리 색상
        fill=True,                      # 원 내부 채우기 여부
        fill_color='red',               # 원 내부 채우기 색상
        fill_opacity=0.4                # 내부 투명도 (겹치는 구역 시인성 확보)
    ).add_to(nasung_map)

parking_filtered = parking_locations[parking_locations['위도'].notna() & parking_locations['경도'].notna()]

for _, row in parking_filtered.iterrows():
    parking_radius = row['주차구획수'] * 0.05
    
    if parking_radius < 4:
        parking_radius = 4
        
    parking_name = row.get('주차장명', '주차시설')
    popup_text = f"<b>[주차장]</b> {parking_name}<br><b>주차구획수:</b> {row['주차구획수']}면"
    
    folium.CircleMarker(
        location=[row['위도'], row['경도']],
        radius=parking_radius,
        popup=folium.Popup(popup_text, max_width=300),
        color='blue',                   
        fill=True,
        fill_color='blue',
        fill_opacity=0.4
    ).add_to(nasung_map)

# 지도 출력
nasung_map.save('../results/nasung_maps.html')

In [31]:
import folium

dodam_map = folium.Map(location=[36.5142496577663, 127.261329157226], zoom_start=16)

df_dodam = df[(df['지역'] == '도담동') & df['위도'].notna() & df['경도'].notna()]

for _, row in df_dodam.iterrows():
    radius_scale = row['단속건수'] * 0.05
    popup_text = f"{row['단속장소']}<br><b>단속건수:</b> {row['단속건수']}건"
    
    folium.CircleMarker(
        location=[row['위도'], row['경도']],
        radius=radius_scale,            # 단속건수별 크기 동적 조절
        popup=folium.Popup(popup_text, max_width=300),
        color='red',                    # 원의 테두리 색상
        fill=True,                      # 원 내부 채우기 여부
        fill_color='red',               # 원 내부 채우기 색상
        fill_opacity=0.4                # 내부 투명도 (겹치는 구역 시인성 확보)
    ).add_to(dodam_map)

parking_filtered = parking_locations[parking_locations['위도'].notna() & parking_locations['경도'].notna()]

for _, row in parking_filtered.iterrows():
    parking_radius = row['주차구획수'] * 0.05
    
    if parking_radius < 4:
        parking_radius = 4
        
    parking_name = row.get('주차장명', '주차시설')
    popup_text = f"<b>[주차장]</b> {parking_name}<br><b>주차구획수:</b> {row['주차구획수']}면"
    
    folium.CircleMarker(
        location=[row['위도'], row['경도']],
        radius=parking_radius,
        popup=folium.Popup(popup_text, max_width=300),
        color='blue',                   
        fill=True,
        fill_color='blue',
        fill_opacity=0.4
    ).add_to(dodam_map)

# 지도 출력
dodam_map.save('../results/dodam_maps.html')

In [32]:
import folium

boram_map = folium.Map(location=[36.4779220963336, 127.291361060307], zoom_start=16)

df_boram = df[(df['지역'] == '보람동') & df['위도'].notna() & df['경도'].notna()]

for _, row in df_boram.iterrows():
    radius_scale = row['단속건수'] * 0.05
    popup_text = f"{row['단속장소']}<br><b>단속건수:</b> {row['단속건수']}건"
    
    folium.CircleMarker(
        location=[row['위도'], row['경도']],
        radius=radius_scale,            # 단속건수별 크기 동적 조절
        popup=folium.Popup(popup_text, max_width=300),
        color='red',                    # 원의 테두리 색상
        fill=True,                      # 원 내부 채우기 여부
        fill_color='red',               # 원 내부 채우기 색상
        fill_opacity=0.4                # 내부 투명도 (겹치는 구역 시인성 확보)
    ).add_to(boram_map)

parking_filtered = parking_locations[parking_locations['위도'].notna() & parking_locations['경도'].notna()]

for _, row in parking_filtered.iterrows():
    parking_radius = row['주차구획수'] * 0.05
    
    if parking_radius < 4:
        parking_radius = 4
        
    parking_name = row.get('주차장명', '주차시설')
    popup_text = f"<b>[주차장]</b> {parking_name}<br><b>주차구획수:</b> {row['주차구획수']}면"
    
    folium.CircleMarker(
        location=[row['위도'], row['경도']],
        radius=parking_radius,
        popup=folium.Popup(popup_text, max_width=300),
        color='blue',                   
        fill=True,
        fill_color='blue',
        fill_opacity=0.4
    ).add_to(boram_map)

# 지도 출력
boram_map.save('../results/boram_maps.html')

In [33]:
import folium

sodam_map = folium.Map(location=[36.4824131895133, 127.30269559169726], zoom_start=16)

df_sodam = df[(df['지역'] == '소담동') & df['위도'].notna() & df['경도'].notna()]

for _, row in df_sodam.iterrows():
    radius_scale = row['단속건수'] * 0.05
    popup_text = f"{row['단속장소']}<br><b>단속건수:</b> {row['단속건수']}건"
    
    folium.CircleMarker(
        location=[row['위도'], row['경도']],
        radius=radius_scale,            # 단속건수별 크기 동적 조절
        popup=folium.Popup(popup_text, max_width=300),
        color='red',                    # 원의 테두리 색상
        fill=True,                      # 원 내부 채우기 여부
        fill_color='red',               # 원 내부 채우기 색상
        fill_opacity=0.4                # 내부 투명도 (겹치는 구역 시인성 확보)
    ).add_to(sodam_map)

parking_filtered = parking_locations[parking_locations['위도'].notna() & parking_locations['경도'].notna()]

for _, row in parking_filtered.iterrows():
    parking_radius = row['주차구획수'] * 0.05
    
    if parking_radius < 4:
        parking_radius = 4
        
    parking_name = row.get('주차장명', '주차시설')
    popup_text = f"<b>[주차장]</b> {parking_name}<br><b>주차구획수:</b> {row['주차구획수']}면"
    
    folium.CircleMarker(
        location=[row['위도'], row['경도']],
        radius=parking_radius,
        popup=folium.Popup(popup_text, max_width=300),
        color='blue',                   
        fill=True,
        fill_color='blue',
        fill_opacity=0.4
    ).add_to(sodam_map)

# 지도 출력
sodam_map.save('../results/sodam_maps.html')

In [ ]:
import folium

arm_map = folium.Map(location=[36.5122327271163, 127.245710155919], zoom_start=16)

df_arm = df[(df['지역'] == '아름동') & df['위도'].notna() & df['경도'].notna()]

for _, row in df_arm.iterrows():
    radius_scale = row['단속건수'] * 0.04
    popup_text = f"{row['단속장소']}<br><b>단속건수:</b> {row['단속건수']}건"
    
    folium.CircleMarker(
        location=[row['위도'], row['경도']],
        radius=radius_scale,            # 단속건수별 크기 동적 조절
        popup=folium.Popup(popup_text, max_width=300),
        color='red',                    # 원의 테두리 색상
        fill=True,                      # 원 내부 채우기 여부
        fill_color='red',               # 원 내부 채우기 색상
        fill_opacity=0.4                # 내부 투명도 (겹치는 구역 시인성 확보)
    ).add_to(arm_map)

parking_filtered = parking_locations[parking_locations['위도'].notna() & parking_locations['경도'].notna()]

for _, row in parking_filtered.iterrows():
    parking_radius = row['주차구획수'] * 0.04
    
    if parking_radius < 4:
        parking_radius = 4
        
    parking_name = row.get('주차장명', '주차시설')
    popup_text = f"<b>[주차장]</b> {parking_name}<br><b>주차구획수:</b> {row['주차구획수']}면"
    
    folium.CircleMarker(
        location=[row['위도'], row['경도']],
        radius=parking_radius,
        popup=folium.Popup(popup_text, max_width=300),
        color='blue',                   
        fill=True,
        fill_color='blue',
        fill_opacity=0.4
    ).add_to(arm_map)

# 지도 출력
arm_map.save('../results/arm_maps.html')

:

In [35]:
import folium

jochiwon_map = folium.Map(location=[36.60107993189985, 127.29626722125276], zoom_start=16)

df_jochiwon = df[(df['지역'] == '조치원읍') & df['위도'].notna() & df['경도'].notna()]

for _, row in df_jochiwon.iterrows():
    radius_scale = row['단속건수'] * 0.05
    popup_text = f"{row['단속장소']}<br><b>단속건수:</b> {row['단속건수']}건"
    
    folium.CircleMarker(
        location=[row['위도'], row['경도']],
        radius=radius_scale,            # 단속건수별 크기 동적 조절
        popup=folium.Popup(popup_text, max_width=300),
        color='red',                    # 원의 테두리 색상
        fill=True,                      # 원 내부 채우기 여부
        fill_color='red',               # 원 내부 채우기 색상
        fill_opacity=0.4                # 내부 투명도 (겹치는 구역 시인성 확보)
    ).add_to(jochiwon_map)

parking_filtered = parking_locations[parking_locations['위도'].notna() & parking_locations['경도'].notna()]

for _, row in parking_filtered.iterrows():
    parking_radius = row['주차구획수'] * 0.05
    
    if parking_radius < 4:
        parking_radius = 4
        
    parking_name = row.get('주차장명', '주차시설')
    popup_text = f"<b>[주차장]</b> {parking_name}<br><b>주차구획수:</b> {row['주차구획수']}면"
    
    folium.CircleMarker(
        location=[row['위도'], row['경도']],
        radius=parking_radius,
        popup=folium.Popup(popup_text, max_width=300),
        color='blue',                   
        fill=True,
        fill_color='blue',
        fill_opacity=0.4
    ).add_to(jochiwon_map)

# 지도 출력
jochiwon_map.save('../results/jochiwon_maps.html')

In [36]:
import folium

hansol_map = folium.Map(location=[36.4776879455274, 127.256765224291], zoom_start=16)

df_hansol = df[(df['지역'] == '한솔동') & df['위도'].notna() & df['경도'].notna()]

for _, row in df_hansol.iterrows():
    radius_scale = row['단속건수'] * 0.07
    popup_text = f"{row['단속장소']}<br><b>단속건수:</b> {row['단속건수']}건"
    
    folium.CircleMarker(
        location=[row['위도'], row['경도']],
        radius=radius_scale,            # 단속건수별 크기 동적 조절
        popup=folium.Popup(popup_text, max_width=300),
        color='red',                    # 원의 테두리 색상
        fill=True,                      # 원 내부 채우기 여부
        fill_color='red',               # 원 내부 채우기 색상
        fill_opacity=0.4                # 내부 투명도 (겹치는 구역 시인성 확보)
    ).add_to(hansol_map)

parking_filtered = parking_locations[parking_locations['위도'].notna() & parking_locations['경도'].notna()]

for _, row in parking_filtered.iterrows():
    parking_radius = row['주차구획수'] * 0.07
    
    if parking_radius < 4:
        parking_radius = 4
        
    parking_name = row.get('주차장명', '주차시설')
    popup_text = f"<b>[주차장]</b> {parking_name}<br><b>주차구획수:</b> {row['주차구획수']}면"
    
    folium.CircleMarker(
        location=[row['위도'], row['경도']],
        radius=parking_radius,
        popup=folium.Popup(popup_text, max_width=300),
        color='blue',                   
        fill=True,
        fill_color='blue',
        fill_opacity=0.4
    ).add_to(hansol_map)

# 지도 출력
hansol_map.save('../results/hansol_maps.html')